DCOEC/Controllers/DCCropsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DCOEC.Models;

namespace DCOEC.Controllers
{
    public class DCCropsController : Controller
    {
        private readonly OECContext _context;

        public DCCropsController(OECContext context)
        {
            _context = context;
            

        }


        // GET: DCCrops
        public async Task<IActionResult> Index(string sortOrder="")
        {

            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.IDSortParm = sortOrder == "ID" ? "ID_desc" : "ID";
            var crops = from c in _context.Crop
                           select c;
            crops.Include(v => v.Variety);
            
            switch (sortOrder)
            {
                case "name_desc":
                    crops = crops.OrderByDescending(s => s.Name);
                    break;
                case "ID":
                    crops = crops.OrderBy(s => s.CropId);
                    break;
                //case "date_desc":
                //    crops = crops.OrderByDescending(s => s.EnrollmentDate);
                //    break;
                default:
                    crops = crops.OrderBy(s => s.Name);
                    break;
            }


            return View(await crops.ToListAsync());


            //return View(await _context.Crop
            //                .OrderBy(a => a.Name)
            //                .ToListAsync());
        }

        // GET: DCCrops/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var crop = await _context.Crop
                .SingleOrDefaultAsync(m => m.CropId == id);
            if (crop == null)
            {
                return NotFound();
            }

            return View(crop);
        }

        // GET: DCCrops/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: DCCrops/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CropId,Name,Image")] Crop crop)
        {
            if (ModelState.IsValid)
            {
                _context.Add(crop);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(crop);
        }

        // GET: DCCrops/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var crop = await _context.Crop.SingleOrDefaultAsync(m => m.CropId == id);
            if (crop == null)
            {
                return NotFound();
            }
            return View(crop);
        }

        // POST: DCCrops/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CropId,Name,Image")] Crop crop)
        {
            if (id != crop.CropId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(crop);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CropExists(crop.CropId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(crop);
        }

        // GET: DCCrops/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var crop = await _context.Crop
                .SingleOrDefaultAsync(m => m.CropId == id);
            if (crop == null)
            {
                return NotFound();
            }

            return View(crop);
        }

        // POST: DCCrops/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var crop = await _context.Crop.SingleOrDefaultAsync(m => m.CropId == id);
            _context.Crop.Remove(crop);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CropExists(int id)
        {
            return _context.Crop.Any(e => e.CropId == id);
        }


        // GET: DCCrops
        public async Task<IActionResult> Test()
        {
            try
            {
                var crops = _context.Crop;
                return View(crops);
            }
            catch (Exception ex)
            {
                while (ex.InnerException != null) ex = ex.InnerException;
                ModelState.AddModelError("", "exception getting Crops from database: " + ex.Message);
                return View(new List<Crop>());
            }


            return View(await _context.Crop.ToListAsync());
        }
    }
}

DCOEC/Controllers/DCPlotsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DCOEC.Models;
using Microsoft.AspNetCore.Http;

namespace DCOEC.Controllers
{
    public class DCPlotsController : Controller
    {
        private readonly OECContext _context;

        public DCPlotsController(OECContext context)
        {
            _context = context;
        }


        const string SessionKeyId = "_Id"; //Crop ID or Variety ID
        const string SessionKeySearchCriteria = "_SearchCriteria";




        ////GET: Plots
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(int? ID, string SearchCriteria = "plot" )  //Only returns where CropId=1 dont get to see other crop ids?
        {
            //SearchCriteria = SearchCriteria ?? ""; //Null search criteria defaults to plot

            //if id and sc are passed store to session
            if (ID != null)
            {


                //Set Session

                // create session variables
                HttpContext.Session.SetInt32(SessionKeyId, Convert.ToInt32(ID));
                HttpContext.Session.SetString(SessionKeySearchCriteria, SearchCriteria);
                TempData["Message"] = "ID and SearchCriteria stored to session.";

            }

            else if ((ID == null ) && (HttpContext.Session.GetInt32(SessionKeyId)) != null)
            {
                //Read from session
                ID = Convert.ToInt32(HttpContext.Session.GetInt32(SessionKeyId));
                SearchCriteria = HttpContext.Session.GetString(SessionKeySearchCriteria);
                TempData["Message"] = "Got ID and search criteria from session.";
            }

            else //Not in Session
            {
                SearchCriteria = "";
                //TempData["Message"] = "No session was found.";
                //return RedirectToAction("Index", "DCPlots");
            }
            

            ////can be extended to fertilizer, treament and Soil likewise
            var oECContext = _context.Plot;

         
            //foreach (var item in oECContext)
            //{
            
            //item.Treatment.OrderBy(a => a.Name);
            
            //}


            switch (SearchCriteria)
            {
                case "farm":
                    return View(await _context.Plot
                                .Include(p => p.Farm)
                                .Include(p => p.Variety)
                                .Include(p => p.Treatment)
                                .Include(p => p.Variety.Crop)
                                .Where(p => p.FarmId == ID)
                                .OrderByDescending(p => p.DatePlanted)
                                 .ToListAsync());

                    ;
                case "variety":
                    return View(await _context.Plot
                                .Include(p => p.Farm)
                                .Include(p => p.Variety)
                                .Include(p => p.Treatment)
                                .Include(p => p.Variety.Crop)
                                .Where(p => p.VarietyId == ID)
                                .OrderByDescending(p => p.DatePlanted)
                                 .ToListAsync());


                    
                case "crop":
                        return View(await _context.Plot
                                .Include(p => p.Farm)
                                .Include(p => p.Variety)
                                .Include(p => p.Treatment)
                                .Include(p => p.Variety.Crop)
                                .Where(p => p.Variety.CropId == ID)
                                .OrderByDescending(p => p.DatePlanted)
                                .ToListAsync());
                case "plot":
                    return View(await _context.Plot
                                .Include(p => p.Farm)
                                .Include(p => p.Variety)
                                .Include(p => p.Treatment)
                                .Include(p => p.Variety.Crop)
                                .Where(p => p.PlotId == ID)
                                .OrderByDescending(p => p.DatePlanted)
                                 .ToListAsync());
                case "":
                    return View(await _context.Plot
                                .Include(p => p.Farm)
                                .Include(p => p.Variety)
                                .Include(p => p.Treatment)
                                .Include(p => p.Variety.Crop)
                                .OrderByDescending(p => p.DatePlanted)
                                 .ToListAsync());


                default:
                    return View(await _context.Plot.Include(p => p.Farm)
                                                    .Include(p => p.Variety)
                                                    .Include(p => p.Treatment)
                                                    .Include(p => p.Variety.Crop)
                                                    .OrderByDescending(p => p.DatePlanted)
                                                     .ToListAsync());
            }


            
        }

        


        // GET: Plots/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var plot = await _context.Plot
                .Include(p => p.Farm)
                .Include(p => p.Variety)
                .SingleOrDefaultAsync(m => m.PlotId == id);
            if (plot == null)
            {
                return NotFound();
            }

            return View(plot);
        }

        // GET: Plots/Create
        public IActionResult Create()
        {
            
            if (HttpContext.Session.GetString(SessionKeySearchCriteria) != null)
            {
                var Id = Convert.ToInt32(HttpContext.Session.GetInt32(SessionKeyId));
                var SearchCriteria = HttpContext.Session.GetString(SessionKeySearchCriteria);


                switch (SearchCriteria)
                {
                    case "farm":
                        break;

                    case "variety":
                        ViewData["VarietyID"] = Id;
                        ViewData["VarietyName"] = SearchCriteria;
                        break;


                    case "crop":

                        //Set View Data
                        ViewData["CropID"] = Id;
                        ViewData["CropName"] = SearchCriteria;
                        break;

                    default:
                        break;
                        
                }
                

                TempData["Message"] = "Got ID and Search Key from session.";

            }



            ViewData["FarmId"] = new SelectList(_context.Farm.OrderBy(x=>x.Name), "FarmId", "Name");
            ViewData["VarietyId"] = new SelectList(_context.Variety.OrderBy(x=>x.Name), "VarietyId", "Name");
            return View();
        }

        // POST: Plots/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PlotId,FarmId,VarietyId,DatePlanted,DateHarvested,PlantingRate,PlantingRateByPounds,RowWidth,PatternRepeats,OrganicMatter,BicarbP,Potassium,Magnesium,Calcium,PHsoil,PHbuffer,Cec,PercentBaseSaturationK,PercentBaseSaturationMg,PercentBaseSaturationCa,PercentBaseSaturationH,Comments")] Plot plot)
        {
            if (ModelState.IsValid)
            {
                if (HttpContext.Session.GetString(SessionKeySearchCriteria) != null)
                {
                    var Id = Convert.ToInt32(HttpContext.Session.GetInt32(SessionKeyId));
                    var SearchCriteria = HttpContext.Session.GetString(SessionKeySearchCriteria);


                    switch (SearchCriteria)
                    {
                        case "farm":
                            break;

                        case "variety":
                            plot.Variety = _context.Variety
                                            .FirstOrDefault(x => x.VarietyId == plot.VarietyId);

                                //_context.Variety.SingleOrDefault(x => x.VarietyId == plot.VarietyId);
                            break;


                        case "crop":
                            plot.Variety.Crop = _context.Crop
                                                 .Include(x => x.Variety)
                                                 .FirstOrDefault (x => x.CropId == plot.Variety.Crop.CropId);

                            break;

                        default:
                            break;

                    }


                }
                
                
                _context.Add(plot);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }


            ViewData["FarmId"] = new SelectList(_context.Farm.OrderBy(x => x.Name), "FarmId", "Name");
            ViewData["VarietyId"] = new SelectList(_context.Variety.OrderBy(x => x.Name), "VarietyId", "Name");


            //ViewData["FarmId"] = new SelectList(_context.Farm, "FarmId", "ProvinceCode", plot.FarmId);
            //ViewData["VarietyId"] = new SelectList(_context.Variety, "VarietyId", "VarietyId", plot.VarietyId);
            return View(plot);
        }

        // GET: Plots/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {

DCOEC/Views/DCVarieties/Create.cshtml
@model DCOEC.Models.Variety
@using Microsoft.AspNetCore.Http


@{
    ViewData["Title"] = "Add a {" + ViewData["CropName"]+"} variety";
}


<h2>Add a {@ViewData["CropName"]} variety</h2>



<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CropId" value="ViewBag.cId"/>
            
            
                        @*<div class="form-group" readonly="readonly">
                    <label asp-for="CropId" readonly="readonly" class="control-label"></label>
                    <select asp-for="CropId" readonly="readonly" class ="form-control" asp-items="ViewBag.CropId"></select>

                    <select id="EmployeeId" name="EmployeeId"  multiple="multiple" asp-items="@ViewBag.Employees">
            <option>Please select</option>
        </select>

                </div>*@
            
            <input type="hidden" name="CropId" value="@ViewBag.cId" />

            @*<select id="CropId" name="CropId" asp-items="@ViewBag.CropId">
                <option>Please select</option>
            </select>*@

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DCOEC/Views/DCVarieties/Delete.cshtml
@model DCOEC.Models.Variety

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Variety</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Crop)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Crop.CropId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="VarietyId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DCOEC/Views/DCVarieties/Details.cshtml
@model DCOEC.Models.Variety

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Variety</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Crop)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Crop.CropId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.VarietyId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

DCOEC/Views/DCVarieties/DisplayVarietiesOfCropID.cshtml
@using DCOEC.Models;
@model IEnumerable<Variety>

@{
    ViewData["Title"] = "Varieties List Of CropID";
}



    <h2>Varieties List for crop:</h2> //How to display CropID here?!




<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
            <th>
                @Html.DisplayNameFor(model => model.Crop)
            </th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Crop.CropId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.VarietyId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.VarietyId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.VarietyId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>


<a asp-controller="DCCrops" asp-action="Index">Back to Crop List</a> 

DCOEC/Views/DCVarieties/Edit.cshtml
@model DCOEC.Models.Variety



@{
    ViewData["Title"] = "Edit {" + ViewData["CropName"] + "} variety";
}


<h2>Edit {@ViewData["CropName"]} variety</h2>




<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input readonly="readonly" asp-for="VarietyId" />
            

            <input type="hidden" name="CropId" value="@ViewBag.cId" />

                 @*<div class="form-group hidden">
                <label asp-for="CropId" class="control-label"></label>
                <select asp-for="CropId" class="form-control" asp-items="ViewBag.CropId"></select>
                <span asp-validation-for="CropId" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DCOEC/Views/DCVarieties/Index.cshtml
@model IEnumerable<DCOEC.Models.Variety>


@{
    ViewData["Title"] = "Varieties of {" + ViewData["CropName"] + "}";
}


<h2>Varieties of {@ViewData["CropName"]}</h2>

CropId = @ViewData["CropID"]

@*Variety ID = @ViewData["VarietyID"]
Variety name = @ViewData["VarietyName"]*@




<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                @*<th>
                    @Html.ActionLink("Variety ID", "Index", new { sortOrder = ViewBag.IDSortParm })
                </th>
                <th>
                    @Html.ActionLink(@Html.DisplayNameFor(model => model.Name), "Index", new { sortOrder = ViewBag.NameSortParm })
                </th>
                <th>
                    @Html.ActionLink("Crop ID","Index", new { sortOrder = ViewBag.CropIDSortParm})
                </th>*@
                
            @*<th>
                @Html.DisplayNameFor(model => model.VarietyId)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.Crop)
            </th>
            
            <th>
                    Crop @Html.DisplayNameFor(model => model.Crop.Name)
                </th>*@
                
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            @*<td>
                @Html.DisplayFor(modelItem => item.VarietyId)
            </td>*@
            <td>
                <a asp-controller="DCPlots" asp-action="Index" asp-route-Id="@item.VarietyId" asp-route-SearchCriteria="variety">
                    @Html.DisplayFor(modelItem => item.Name)
                </a>
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.CropId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Crop.Name)
            </td>*@
            <td>
                <a asp-action="Edit" asp-route-id="@item.VarietyId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.VarietyId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.VarietyId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>