DCOEC/Controllers/DCCropsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DCOEC.Models;

namespace DCOEC.Controllers
{
    public class DCCropsController : Controller
    {
        private readonly OECContext _context;

        public DCCropsController(OECContext context)
        {
            _context = context;
            

        }


        // GET: DCCrops
        public async Task<IActionResult> Index(string sortOrder="")
        {

            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.IDSortParm = sortOrder == "ID" ? "ID_desc" : "ID";
            var crops = from c in _context.Crop
                           select c;
            crops.Include(v => v.Variety);
            
            switch (sortOrder)
            {
                case "name_desc":
                    crops = crops.OrderByDescending(s => s.Name);
                    break;
                case "ID":
                    crops = crops.OrderBy(s => s.CropId);
                    break;
                //case "date_desc":
                //    crops = crops.OrderByDescending(s => s.EnrollmentDate);
                //    break;
                default:
                    crops = crops.OrderBy(s => s.Name);
                    break;
            }


            return View(await crops.ToListAsync());


            //return View(await _context.Crop
            //                .OrderBy(a => a.Name)
            //                .ToListAsync());
        }

        // GET: DCCrops/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var crop = await _context.Crop
                .SingleOrDefaultAsync(m => m.CropId == id);
            if (crop == null)
            {
                return NotFound();
            }

            return View(crop);
        }

        // GET: DCCrops/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: DCCrops/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CropId,Name,Image")] Crop crop)
        {
            if (ModelState.IsValid)
            {
                _context.Add(crop);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(crop);
        }

        // GET: DCCrops/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var crop = await _context.Crop.SingleOrDefaultAsync(m => m.CropId == id);
            if (crop == null)
            {
                return NotFound();
            }
            return View(crop);
        }

        // POST: DCCrops/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CropId,Name,Image")] Crop crop)
        {
            if (id != crop.CropId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(crop);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CropExists(crop.CropId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(crop);
        }

        // GET: DCCrops/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var crop = await _context.Crop
                .SingleOrDefaultAsync(m => m.CropId == id);
            if (crop == null)
            {
                return NotFound();
            }

            return View(crop);
        }

        // POST: DCCrops/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var crop = await _context.Crop.SingleOrDefaultAsync(m => m.CropId == id);
            _context.Crop.Remove(crop);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CropExists(int id)
        {
            return _context.Crop.Any(e => e.CropId == id);
        }


        // GET: DCCrops
        public async Task<IActionResult> Test()
        {
            try
            {
                var crops = _context.Crop;
                return View(crops);
            }
            catch (Exception ex)
            {
                while (ex.InnerException != null) ex = ex.InnerException;
                ModelState.AddModelError("", "exception getting Crops from database: " + ex.Message);
                return View(new List<Crop>());
            }


            return View(await _context.Crop.ToListAsync());
        }
    }
}

DCOEC/Controllers/DCFarmsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DCOEC.Models;

namespace DCOEC.Controllers
{
    public class DCFarmsController : Controller
    {
        private readonly OECContext _context;

        public DCFarmsController(OECContext context)
        {
            _context = context;
        }

        // GET: DCFarms
        public async Task<IActionResult> Index()
        {
            var oECContext = _context.Farm
                .Include(f => f.ProvinceCodeNavigation)
                .OrderBy(x => x.Name);
            return View(await oECContext.ToListAsync());
        }

        // GET: DCFarms/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var farm = await _context.Farm
                .Include(f => f.ProvinceCodeNavigation)
                .SingleOrDefaultAsync(m => m.FarmId == id);
            if (farm == null)
            {
                return NotFound();
            }

            return View(farm);
        }

        // GET: DCFarms/Create
        public IActionResult Create()
        {
            ViewData["ProvinceCode"] = new SelectList(_context.Province, "ProvinceCode", "ProvinceCode");
            return View();
        }

        // POST: DCFarms/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FarmId,Name,Address,Town,County,ProvinceCode,PostalCode,HomePhone,CellPhone,Email,Directions,DateJoined,LastContactDate")] Farm farm)
        {
                try
                {
                if (ModelState.IsValid)
                {
                    _context.Add(farm);
                    await _context.SaveChangesAsync();
                    TempData["Message"] = "New record.. Saved";
                    return RedirectToAction(nameof(Index));
                }
                }
                catch (Exception Ex)
                {
              
                TempData["Message"] = Ex.InnerException.Message;
                ModelState.AddModelError("InnerException", Ex.InnerException.Message);
                }
                //return RedirectToAction(nameof(Index));
           
            ViewData["ProvinceCode"] = new SelectList(_context.Province, "ProvinceCode", "ProvinceCode", farm.ProvinceCode);
            return View(farm);
        }

        // GET: DCFarms/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var farm = await _context.Farm.SingleOrDefaultAsync(m => m.FarmId == id);
            if (farm == null)
            {
                return NotFound();
            }
            ViewData["ProvinceCode"] = new SelectList(_context.Province.OrderBy(x => x.Name), "ProvinceCode", "Name", farm.ProvinceCode);

            return View(farm);
        }

        // POST: DCFarms/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FarmId,Name,Address,Town,County,ProvinceCode,PostalCode,HomePhone,CellPhone,Email,Directions,DateJoined,LastContactDate")] Farm farm)
        {
            if (id != farm.FarmId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(farm);
                    await _context.SaveChangesAsync();
                    TempData["Message"] = "Edit Changes.. Saved";
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FarmExists(farm.FarmId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                catch (Exception Ex)
                {
                    TempData["Message"] = Ex.InnerException;
                    ModelState.AddModelError("InnerException", Ex.InnerException.Message);
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProvinceCode"] = new SelectList(_context.Province.OrderBy(x => x.Name), "ProvinceCode", "Name", farm.ProvinceCode);
            return View(farm);
        }

        // GET: DCFarms/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var farm = await _context.Farm
                .Include(f => f.ProvinceCodeNavigation)
                .SingleOrDefaultAsync(m => m.FarmId == id);
            if (farm == null)
            {
                return NotFound();
            }

            return View(farm);
        }

        // POST: DCFarms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var farm = await _context.Farm.SingleOrDefaultAsync(m => m.FarmId == id);
            _context.Farm.Remove(farm);
            try
            {
                await _context.SaveChangesAsync();
            }
            catch(Exception ex)
            {
                TempData["Message"] = ex.InnerException.Message;
            }
            TempData["Message"] = "Delete success";
            return RedirectToAction(nameof(Index));
        }

        private bool FarmExists(int id)
        {
            return _context.Farm.Any(e => e.FarmId == id);
        }
    }
}

DCOEC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OEC by Dinesh</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    @* Including Materialzecss

    <environment include="Development, Staging, Production">

        <!-- Compiled and minified CSS -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

    </environment>

    *@


</head>
<body>
 


    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="navbar-header">
                        <img src="~/images/farmer.jpg" height="100" class="" alt="OEC Fertilizers">
                <a  asp-area="" asp-controller="Home" asp-action="Index"  class="navbar-brand">
                    OEC Fertilizers
                    
                </a>
                </div>

               
            </div>
            <div>
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="DCCrops" asp-action="Index">Crops</a></li>
                    <li><a asp-area="" asp-controller="DCFertilizers" asp-action="Index">Fertilizers</a></li>
                    @*<li><a asp-area="" asp-controller="DCVarieties" asp-action="Index">Varieties</a></li>
                    <li><a asp-area="" asp-controller="DCPlots" asp-action="Index">Plots</a></li>
                    <li><a asp-area="" asp-controller="DCTreatments" asp-action="Index">Treatments</a></li>*@
                    <li><a asp-area="" asp-controller="DCFarms" asp-action="Index">Farms</a></li>


                    

                    @*<li><a href="/DCCrops/index">Using HTML Tag</a></li>  
                    <li>@Html.ActionLink("Using HTML Helpers", "Index", "Home")</li>
                    <li>
                        <a asp-controller="DCFertilizers" , asp-action="Index">
                            Using Tag Helpers
                        </a>
                    </li>*@
                   
                </ul>

                


                @await Html.PartialAsync("_LoginPartial")
               

            </div>
        </div>
    </nav>


 

    <div class="container body-content">
        <div>
            <h3 class="alert-danger">@TempData["Message"]</h3>

        </div>
     
        @RenderBody()
        <hr />
        <footer>
            <p>
                &copy; 2017 - OEC by
                <a href="mailto:dinesh.condur@gmail.com?Subject=Hello%20again" target="_top">Dinesh Condur</a> CAD
                <a class="pull-right" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                <a class="pull-right" asp-area="" asp-controller="Home" asp-action="About">About &nbsp;</a>
               
                
            </p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>

    <environment include="Development, Staging, Production">

        <!-- Compiled and minified JavaScript -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>

    </environment>

    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>